version: '3'
services:
  web:
    image: python:3.9-slim-buster
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    environment:
      PYTHONUNBUFFERED: 1
    command: sh -c "pip install -r requirements.txt && python manage.py runserver 0.0.0.0:3001"