# Generated by Django 4.1.1 on 2023-03-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("locationName", models.CharField(max_length=100)),
                ("lattitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longtitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("linkVideo", models.URLField()),
                ("uid", models.PositiveIntegerField()),
                ("jobId", models.PositiveIntegerField()),
                ("status", models.TextField()),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
