# Generated by Django 4.1.1 on 2023-03-22 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_jobtask"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobtask", old_name="lattitude", new_name="latitude",
        ),
    ]
